name: BedHunt
version: 0.1
api-version: 1.14
authors: [Australian, Jelly_Squid]
main: mc.samios.io.BedHunt.Main
commands:
  info:
    description: Displays rules and gameplay information of BedHunt
    usage: /info
  cube:
    description: Test
  removebed:
    description: Removes a bed
    aliases: [rb]
  deathmatch:
    description: Destroys all beds and begins deathmatch stage (where nobody can respawn and border shrinks)
    aliases: [dm]
  rules:
    description: Shows the BedHunt rules
  gameplay:
    description: Shows the BedHunt gameplay instructions.
  modifier:
    description: Allows enabling/disabling of game modifiers. Admin only.
    aliases: [md]
  game:
    description: Allows game to be started and stopped via an Admin.

